apiVersion: v2
name: infrastructure
description: Shared infrastructure for The Edge Story (PostgreSQL, Redis, Kafka)
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
  - name: postgresql
    version: 18.0.7
    repository: https://charts.bitnami.com/bitnami

  - name: redis
    version: 23.0.10
    repository: https://charts.bitnami.com/bitnami

  - name: kafka
    version: 32.4.3
    repository: https://charts.bitnami.com/bitnami
