apiVersion: v2
name: infrastructure
description: Shared infrastructure for The Edge Story (PostgreSQL, Redis, Kafka)
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
  - name: postgresql
    version: 16.4.0
    repository: https://charts.bitnami.com/bitnami

  - name: redis
    version: 20.6.0
    repository: https://charts.bitnami.com/bitnami

  - name: kafka
    version: 31.0.0
    repository: https://charts.bitnami.com/bitnami
