apiVersion: v1
kind: Secret
metadata:
  name: authentik-redis
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  AUTHENTIK_REDIS__HOST: "redis-0.redis.infrastructure.svc.cluster.local"
  AUTHENTIK_REDIS__PORT: "6379"
  AUTHENTIK_REDIS__DB: "1"
  AUTHENTIK_REDIS__PASSWORD: "CHANGE_ME_redis_password"
