apiVersion: v1
kind: Secret
metadata:
  name: authentik-redis
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  AUTHENTIK_REDIS__HOST: "10.42.0.88"
  AUTHENTIK_REDIS__PORT: "6379"
  AUTHENTIK_REDIS__DB: "1"
  AUTHENTIK_REDIS__PASSWORD: "redis-password-2024"
