apiVersion: v1
kind: Secret
metadata:
  name: authentik-redis
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  AUTHENTIK_REDIS__HOST: "infrastructure-redis-master.infrastructure.svc.cluster.local"
  AUTHENTIK_REDIS__PORT: "6379"
  AUTHENTIK_REDIS__DB: "1"
