apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      operator.min.io/authors: MinIO, Inc.
      operator.min.io/license: AGPLv3
      operator.min.io/support: https://subnet.min.io
    generateName: minio-operator-7697f69655-
    labels:
      app.kubernetes.io/instance: minio-operator
      app.kubernetes.io/name: operator
      name: minio-operator
      operator: leader
      pod-template-hash: 7697f69655
    name: minio-operator-7697f69655-zvv64
    namespace: minio-operator
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: minio-operator-7697f69655
  spec:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: name
              operator: In
              values:
              - minio-operator
          topologyKey: kubernetes.io/hostname
    containers:
    - args:
      - controller
      env:
      - name: MINIO_CONSOLE_TLS_ENABLE
        value: "off"
      - name: OPERATOR_STS_ENABLED
        value: "on"
      image: minio/operator:v7.1.1
      imagePullPolicy: IfNotPresent
      name: minio-operator
      resources:
        requests:
          cpu: 200m
          ephemeral-storage: 500Mi
          memory: 256Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-2tnn5
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: ubuntu-16gb-hel1-1
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: minio-operator
    serviceAccountName: minio-operator
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-2tnn5
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2025-10-06T02:01:38Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2025-10-06T02:01:34Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2025-10-06T02:01:38Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2025-10-06T02:01:38Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2025-10-06T02:01:34Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - allocatedResources:
        cpu: 200m
        ephemeral-storage: 500Mi
        memory: 256Mi
      containerID: containerd://ad34a32369ac1bf253ff4a3ebfe91d21cd3a6213e8f11de5a5ad3dfe0d84d64a
      image: docker.io/minio/operator:v7.1.1
      imageID: docker.io/minio/operator@sha256:cd587f60c43dab75799370ad7b6c55f53cfa2188e85f4c5eda939591f8769f47
      lastState: {}
      name: minio-operator
      ready: true
      resources:
        requests:
          cpu: 200m
          ephemeral-storage: 500Mi
          memory: 256Mi
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2025-10-06T02:01:38Z"
      user:
        linux:
          gid: 1000
          supplementalGroups:
          - 1000
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-2tnn5
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 46.62.223.198
    hostIPs:
    - ip: 46.62.223.198
    - ip: 2a01:4f9:c013:abef::1
    phase: Running
    podIP: 10.42.0.39
    podIPs:
    - ip: 10.42.0.39
    qosClass: Burstable
    startTime: "2025-10-06T02:01:34Z"
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"operator.min.io/authors":"MinIO, Inc.","operator.min.io/license":"AGPLv3","operator.min.io/support":"https://subnet.min.io"},"labels":{"app.kubernetes.io/instance":"minio-operator","app.kubernetes.io/name":"operator","name":"minio-operator"},"name":"operator","namespace":"minio-operator"},"spec":{"ports":[{"name":"http","port":4221}],"selector":{"name":"minio-operator","operator":"leader"},"type":"ClusterIP"}}
      operator.min.io/authors: MinIO, Inc.
      operator.min.io/license: AGPLv3
      operator.min.io/support: https://subnet.min.io
    labels:
      app.kubernetes.io/instance: minio-operator
      app.kubernetes.io/name: operator
      name: minio-operator
    name: operator
    namespace: minio-operator
  spec:
    clusterIP: 10.43.41.73
    clusterIPs:
    - 10.43.41.73
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 4221
      protocol: TCP
      targetPort: 4221
    selector:
      name: minio-operator
      operator: leader
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"operator.min.io/authors":"MinIO, Inc.","operator.min.io/license":"AGPLv3","operator.min.io/support":"https://subnet.min.io"},"labels":{"name":"minio-operator"},"name":"sts","namespace":"minio-operator"},"spec":{"ports":[{"name":"https","port":4223,"targetPort":4223}],"selector":{"name":"minio-operator"},"type":"ClusterIP"}}
      operator.min.io/authors: MinIO, Inc.
      operator.min.io/license: AGPLv3
      operator.min.io/support: https://subnet.min.io
    labels:
      name: minio-operator
    name: sts
    namespace: minio-operator
  spec:
    clusterIP: 10.43.145.78
    clusterIPs:
    - 10.43.145.78
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 4223
      protocol: TCP
      targetPort: 4223
    selector:
      name: minio-operator
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"operator.min.io/authors":"MinIO, Inc.","operator.min.io/license":"AGPLv3","operator.min.io/support":"https://subnet.min.io"},"labels":{"app.kubernetes.io/instance":"minio-operator","app.kubernetes.io/name":"operator"},"name":"minio-operator","namespace":"minio-operator"},"spec":{"replicas":2,"selector":{"matchLabels":{"name":"minio-operator"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"operator.min.io/authors":"MinIO, Inc.","operator.min.io/license":"AGPLv3","operator.min.io/support":"https://subnet.min.io"},"labels":{"app.kubernetes.io/instance":"minio-operator","app.kubernetes.io/name":"operator","name":"minio-operator"}},"spec":{"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"name","operator":"In","values":["minio-operator"]}]},"topologyKey":"kubernetes.io/hostname"}]}},"containers":[{"args":["controller"],"env":[{"name":"MINIO_CONSOLE_TLS_ENABLE","value":"off"},{"name":"OPERATOR_STS_ENABLED","value":"on"}],"image":"minio/operator:v7.1.1","imagePullPolicy":"IfNotPresent","name":"minio-operator","resources":{"requests":{"cpu":"200m","ephemeral-storage":"500Mi","memory":"256Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"runAsGroup":1000,"runAsNonRoot":true,"runAsUser":1000,"seccompProfile":{"type":"RuntimeDefault"}}}],"serviceAccountName":"minio-operator"}}}}
      operator.min.io/authors: MinIO, Inc.
      operator.min.io/license: AGPLv3
      operator.min.io/support: https://subnet.min.io
    labels:
      app.kubernetes.io/instance: minio-operator
      app.kubernetes.io/name: operator
    name: minio-operator
    namespace: minio-operator
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        name: minio-operator
    strategy:
      type: Recreate
    template:
      metadata:
        annotations:
          operator.min.io/authors: MinIO, Inc.
          operator.min.io/license: AGPLv3
          operator.min.io/support: https://subnet.min.io
        labels:
          app.kubernetes.io/instance: minio-operator
          app.kubernetes.io/name: operator
          name: minio-operator
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - minio-operator
              topologyKey: kubernetes.io/hostname
        containers:
        - args:
          - controller
          env:
          - name: MINIO_CONSOLE_TLS_ENABLE
            value: "off"
          - name: OPERATOR_STS_ENABLED
            value: "on"
          image: minio/operator:v7.1.1
          imagePullPolicy: IfNotPresent
          name: minio-operator
          resources:
            requests:
              cpu: 200m
              ephemeral-storage: 500Mi
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: minio-operator
        serviceAccountName: minio-operator
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-10-06T09:02:21Z"
      lastUpdateTime: "2025-10-06T09:02:21Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-10-06T09:02:21Z"
      lastUpdateTime: "2025-10-06T09:02:21Z"
      message: ReplicaSet "minio-operator-7697f69655" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "1"
      deployment.kubernetes.io/revision: "1"
      operator.min.io/authors: MinIO, Inc.
      operator.min.io/license: AGPLv3
      operator.min.io/support: https://subnet.min.io
    labels:
      app.kubernetes.io/instance: minio-operator
      app.kubernetes.io/name: operator
      name: minio-operator
      pod-template-hash: 7697f69655
    name: minio-operator-7697f69655
    namespace: minio-operator
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: minio-operator
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: minio-operator
        pod-template-hash: 7697f69655
    template:
      metadata:
        annotations:
          operator.min.io/authors: MinIO, Inc.
          operator.min.io/license: AGPLv3
          operator.min.io/support: https://subnet.min.io
        labels:
          app.kubernetes.io/instance: minio-operator
          app.kubernetes.io/name: operator
          name: minio-operator
          pod-template-hash: 7697f69655
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - minio-operator
              topologyKey: kubernetes.io/hostname
        containers:
        - args:
          - controller
          env:
          - name: MINIO_CONSOLE_TLS_ENABLE
            value: "off"
          - name: OPERATOR_STS_ENABLED
            value: "on"
          image: minio/operator:v7.1.1
          imagePullPolicy: IfNotPresent
          name: minio-operator
          resources:
            requests:
              cpu: 200m
              ephemeral-storage: 500Mi
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: minio-operator
        serviceAccountName: minio-operator
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIBdzCCAR2gAwIBAgIBADAKBggqhkjOPQQDAjAjMSEwHwYDVQQDDBhrM3Mtc2Vy
      dmVyLWNhQDE3NTk3MTE0NTkwHhcNMjUxMDA2MDA0NDE5WhcNMzUxMDA0MDA0NDE5
      WjAjMSEwHwYDVQQDDBhrM3Mtc2VydmVyLWNhQDE3NTk3MTE0NTkwWTATBgcqhkjO
      PQIBBggqhkjOPQMBBwNCAARqGCXrxGpCMBkpMFvc0L21JXhiw3vTnT+gHqVRkI37
      9yo8rZpCpmRxhpdn0DzIu3w2jDUBqRRUhd9BMc2zu8wDo0IwQDAOBgNVHQ8BAf8E
      BAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUeZJG2OGuD6C3OiA9qA17
      dHxqCPUwCgYIKoZIzj0EAwIDSAAwRQIhAPnZhOfemvbu3wUUCI39bFiqaPoHp+jS
      mbHSD/JWBs3qAiAoPvUgbQvHvHEr0IrqNFFJvNOFecO+OwFznWbGebi9Qw==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    name: kube-root-ca.crt
    namespace: minio-operator
kind: List
metadata:
