apiVersion: v2
name: kafka-setup
description: Kafka deployment with automatic topic creation
type: application
version: 0.1.0
appVersion: "3.5"
dependencies:
  - name: kafka
    version: 25.3.3
    repository: https://charts.bitnami.com/bitnami