apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-pipeline
  template:
    metadata:
      labels:
        app: core-pipeline
    spec:
      containers:
        - name: core-pipeline
          image: ghcr.io/uz0/core-pipeline:latest
          ports:
            - containerPort: 3000
