{{- if .Values.imagePullSecrets }}
{{- if .Values.ghcrCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "core-pipeline.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"ghcr.io\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.ghcrCredentials.username .Values.ghcrCredentials.password (printf "%s:%s" .Values.ghcrCredentials.username .Values.ghcrCredentials.password | b64enc) | b64enc }}
{{- end }}
{{- end }}