{{- if .Values.ingress.enabled }}
{{- if .Values.ingress.altHost }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "core-pipeline.fullname" . }}-alt
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "core-pipeline.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.altHost }}
    secretName: {{ include "core-pipeline.fullname" . }}-alt-tls
  {{- end }}
  rules:
  - host: {{ .Values.ingress.altHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "core-pipeline.fullname" . }}
            port:
              number: 80
{{- end }}
{{- end }}
