{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core-pipeline.fullname" . }}-secret
  labels:
    {{- include "core-pipeline.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}