{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "core-pipeline.fullname" . }}
  labels:
    {{- include "core-pipeline.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "core-pipeline.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}