apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing-page
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - host: theedgestory.org
    http:
      paths:
      - backend:
          service:
            name: landing-page
            port:
              number: 80
        path: /
        pathType: Prefix
