---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: minio-admin-stripprefix
  namespace: minio
spec:
  stripPrefix:
    prefixes:
      - /admin

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-s3-admin
  namespace: minio
  annotations:
    cert-manager.io/cluster-issuer: theedgestory
    traefik.ingress.kubernetes.io/router.middlewares: minio-minio-admin-stripprefix@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: s3.theedgestory.org
    http:
      paths:
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: minio-tenant-console
            port:
              number: 9090
  tls:
  - hosts:
    - s3.theedgestory.org
    secretName: minio-s3-tls
