---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: minio-console-redirect
  namespace: minio
spec:
  redirectRegex:
    regex: "^https://minio-console\\.theedgestory\\.org/(.*)"
    replacement: "https://s3.theedgestory.org/admin/${1}"
    permanent: true

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console
  namespace: minio
  annotations:
    cert-manager.io/cluster-issuer: theedgestory
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.middlewares: minio-minio-console-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: minio-console.theedgestory.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-tenant-console
            port:
              number: 9090
  tls:
  - hosts:
    - minio-console.theedgestory.org
    secretName: minio-console-tls
